1st part of transfer learning
SebChw/ART-Templates pull request #27
Opened 2023-11-09 15:25 UTC by kordc

the bert model doesnt work

2023-11-09 15:31 UTC, kordc commented
https://github.com/SebChw/art/pull/150

2023-11-18 14:17 UTC, SebChw commented
I get device mismatch error from the beginning of using HF model
![image](https://github.com/SebChw/ART-Templates/assets/66476124/f3271bef-a955-40d1-b948-64a5c64a46fb)

2023-11-18 17:36 UTC, SebChw requested changes

2023-11-18 17:39 UTC, kordc commented on {{cookiecutter.project_slug}}/tutorial.ipynb
> +    "!pip install art nltk wordcloud"
Oh sure... I'll do `art-training` install

2023-11-18 17:40 UTC, kordc commented on {{cookiecutter.project_slug}}/tutorial.ipynb
> +    "                                      logger=logger\n",
Yeah, I deleted the logger but not the argument itself, thanks

2023-11-18 17:40 UTC, kordc commented on {{cookiecutter.project_slug}}/models/bert.py
> +        inputs = self.tokenizer(
Okay, I'll try

2023-11-21 11:28 UTC, closed without merging